version: "3"
services:
  artemis:
    image: vromero/activemq-artemis:2.14.0
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      DISABLE_SECURITY: "true"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: partners_db
